# Generated by Django 3.1 on 2020-10-29 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201029_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentphoto',
            old_name='images',
            new_name='image',
        ),
    ]
