# Generated by Django 3.1 on 2020-11-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201029_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPhoto',
        ),
    ]
