# Generated by Django 3.1 on 2020-11-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_commentphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
