# Generated by Django 3.1 on 2020-11-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20201117_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='photocomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
