# Generated by Django 3.1 on 2020-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20201209_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poster_picture',
            field=models.ImageField(blank=True, default='poster_default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_default.jpg', null=True, upload_to=''),
        ),
    ]
